# Generated by Django 3.2.23 on 2024-02-01 00:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPersona',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.TextField()),
                ('similarity', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Thread',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utterance',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('talker', models.CharField(max_length=128)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptHandleAPI.thread')),
            ],
        ),
        migrations.CreateModel(
            name='UserPersona',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('persona', models.TextField()),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptHandleAPI.thread')),
                ('utterance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptHandleAPI.utterance')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
