# Generated by Django 3.2.23 on 2024-02-01 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chatgptHandleAPI', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systempersona',
            name='thread',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptHandleAPI.thread'),
        ),
        migrations.AddField(
            model_name='systempersona',
            name='utterance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chatgptHandleAPI.utterance'),
        ),
    ]
